// 120 area-page candidates from SEO-AREA-AND-KEYWORD-REGISTER.md.
// These are DRAFT records. No geography, PINs or coordinates are fabricated —
// lat/lng/boundary remain null until sourced from a licensed provider.
export type AcquisitionGroup =
  | "north" | "south" | "east" | "west" | "central" | "outer";

export interface AreaCandidate {
  id: string;      // 001..120
  name: string;
  slug: string;
  group: AcquisitionGroup;
  aliases?: string[];
}

export const AREA_CANDIDATES: AreaCandidate[] = [
  // North
  { id: "001", name: "Hebbal", slug: "hebbal", group: "north" },
  { id: "002", name: "Hebbal Kempapura", slug: "hebbal-kempapura", group: "north" },
  { id: "003", name: "Yelahanka", slug: "yelahanka", group: "north" },
  { id: "004", name: "Yelahanka New Town", slug: "yelahanka-new-town", group: "north" },
  { id: "005", name: "Jakkur", slug: "jakkur", group: "north" },
  { id: "006", name: "Sahakara Nagar", slug: "sahakara-nagar", group: "north" },
  { id: "007", name: "Kodigehalli", slug: "kodigehalli", group: "north" },
  { id: "008", name: "Vidyaranyapura", slug: "vidyaranyapura", group: "north" },
  { id: "009", name: "Doddabommasandra", slug: "doddabommasandra", group: "north" },
  { id: "010", name: "Jalahalli", slug: "jalahalli", group: "north" },
  { id: "011", name: "Yeshwanthpur", slug: "yeshwanthpur", group: "north", aliases: ["Yeshwantpur"] },
  { id: "012", name: "Mathikere", slug: "mathikere", group: "north" },
  { id: "013", name: "RMV 2nd Stage", slug: "rmv-2nd-stage", group: "north" },
  { id: "014", name: "Sanjaynagar", slug: "sanjaynagar", group: "north" },
  { id: "015", name: "RT Nagar", slug: "rt-nagar", group: "north" },
  { id: "016", name: "Ganganagar", slug: "ganganagar", group: "north" },
  { id: "017", name: "Hennur", slug: "hennur", group: "north" },
  { id: "018", name: "Thanisandra", slug: "thanisandra", group: "north" },
  { id: "019", name: "Nagavara", slug: "nagavara", group: "north" },
  { id: "020", name: "Kalyan Nagar", slug: "kalyan-nagar", group: "north" },
  // South / Southeast
  { id: "021", name: "Jayanagar", slug: "jayanagar", group: "south" },
  { id: "022", name: "JP Nagar", slug: "jp-nagar", group: "south" },
  { id: "023", name: "BTM Layout", slug: "btm-layout", group: "south", aliases: ["BTM"] },
  { id: "024", name: "HSR Layout", slug: "hsr-layout", group: "south", aliases: ["HSR"] },
  { id: "025", name: "Koramangala", slug: "koramangala", group: "south" },
  { id: "026", name: "Banashankari", slug: "banashankari", group: "south" },
  { id: "027", name: "Basavanagudi", slug: "basavanagudi", group: "south" },
  { id: "028", name: "Padmanabhanagar", slug: "padmanabhanagar", group: "south" },
  { id: "029", name: "Kumaraswamy Layout", slug: "kumaraswamy-layout", group: "south" },
  { id: "030", name: "Uttarahalli", slug: "uttarahalli", group: "south" },
  { id: "031", name: "Konanakunte", slug: "konanakunte", group: "south" },
  { id: "032", name: "Anjanapura", slug: "anjanapura", group: "south" },
  { id: "033", name: "Arekere", slug: "arekere", group: "south" },
  { id: "034", name: "Hulimavu", slug: "hulimavu", group: "south" },
  { id: "035", name: "Gottigere", slug: "gottigere", group: "south" },
  { id: "036", name: "Begur", slug: "begur", group: "south" },
  { id: "037", name: "Bommanahalli", slug: "bommanahalli", group: "south" },
  { id: "038", name: "Hongasandra", slug: "hongasandra", group: "south" },
  { id: "039", name: "Singasandra", slug: "singasandra", group: "south" },
  { id: "040", name: "Kudlu", slug: "kudlu", group: "south" },
  // East
  { id: "041", name: "Whitefield", slug: "whitefield", group: "east" },
  { id: "042", name: "Kadugodi", slug: "kadugodi", group: "east" },
  { id: "043", name: "Hoodi", slug: "hoodi", group: "east" },
  { id: "044", name: "Brookefield", slug: "brookefield", group: "east" },
  { id: "045", name: "Kundalahalli", slug: "kundalahalli", group: "east" },
  { id: "046", name: "Marathahalli", slug: "marathahalli", group: "east" },
  { id: "047", name: "Munnekollal", slug: "munnekollal", group: "east" },
  { id: "048", name: "Panathur", slug: "panathur", group: "east" },
  { id: "049", name: "Kadubeesanahalli", slug: "kadubeesanahalli", group: "east" },
  { id: "050", name: "Bellandur", slug: "bellandur", group: "east" },
  { id: "051", name: "Devarabeesanahalli", slug: "devarabeesanahalli", group: "east" },
  { id: "052", name: "Domlur", slug: "domlur", group: "east" },
  { id: "053", name: "Indiranagar", slug: "indiranagar", group: "east" },
  { id: "054", name: "HAL 2nd Stage", slug: "hal-2nd-stage", group: "east" },
  { id: "055", name: "CV Raman Nagar", slug: "cv-raman-nagar", group: "east" },
  { id: "056", name: "Kaggadasapura", slug: "kaggadasapura", group: "east" },
  { id: "057", name: "Vignan Nagar", slug: "vignan-nagar", group: "east" },
  { id: "058", name: "KR Puram", slug: "kr-puram", group: "east" },
  { id: "059", name: "Ramamurthy Nagar", slug: "ramamurthy-nagar", group: "east" },
  { id: "060", name: "Mahadevapura", slug: "mahadevapura", group: "east" },
  // West
  { id: "061", name: "Rajajinagar", slug: "rajajinagar", group: "west" },
  { id: "062", name: "Vijayanagar", slug: "vijayanagar", group: "west" },
  { id: "063", name: "Basaveshwaranagar", slug: "basaveshwaranagar", group: "west" },
  { id: "064", name: "Nagarabhavi", slug: "nagarabhavi", group: "west" },
  { id: "065", name: "Chandra Layout", slug: "chandra-layout", group: "west" },
  { id: "066", name: "Attiguppe", slug: "attiguppe", group: "west" },
  { id: "067", name: "RPC Layout", slug: "rpc-layout", group: "west" },
  { id: "068", name: "Kengeri", slug: "kengeri", group: "west" },
  { id: "069", name: "Kengeri Satellite Town", slug: "kengeri-satellite-town", group: "west" },
  { id: "070", name: "Rajarajeshwari Nagar", slug: "rajarajeshwari-nagar", group: "west", aliases: ["RR Nagar"] },
  { id: "071", name: "Jnanabharathi", slug: "jnanabharathi", group: "west" },
  { id: "072", name: "Ullal", slug: "ullal", group: "west" },
  { id: "073", name: "Sunkadakatte", slug: "sunkadakatte", group: "west" },
  { id: "074", name: "Kamakshipalya", slug: "kamakshipalya", group: "west" },
  { id: "075", name: "Laggere", slug: "laggere", group: "west" },
  { id: "076", name: "Nandini Layout", slug: "nandini-layout", group: "west" },
  { id: "077", name: "Peenya", slug: "peenya", group: "west" },
  { id: "078", name: "Dasarahalli", slug: "dasarahalli", group: "west" },
  { id: "079", name: "Bagalakunte", slug: "bagalakunte", group: "west" },
  { id: "080", name: "Hegganahalli", slug: "hegganahalli", group: "west" },
  // Central
  { id: "081", name: "Malleshwaram", slug: "malleshwaram", group: "central", aliases: ["Malleswaram"] },
  { id: "082", name: "Seshadripuram", slug: "seshadripuram", group: "central" },
  { id: "083", name: "Vasanth Nagar", slug: "vasanth-nagar", group: "central" },
  { id: "084", name: "Sadashivanagar", slug: "sadashivanagar", group: "central" },
  { id: "085", name: "Shivajinagar", slug: "shivajinagar", group: "central" },
  { id: "086", name: "Ulsoor", slug: "ulsoor", group: "central", aliases: ["Halasuru"] },
  { id: "087", name: "Frazer Town", slug: "frazer-town", group: "central", aliases: ["Pulakeshinagar"] },
  { id: "088", name: "Cox Town", slug: "cox-town", group: "central" },
  { id: "089", name: "Cooke Town", slug: "cooke-town", group: "central" },
  { id: "090", name: "Benson Town", slug: "benson-town", group: "central" },
  { id: "091", name: "Richmond Town", slug: "richmond-town", group: "central" },
  { id: "092", name: "Langford Town", slug: "langford-town", group: "central" },
  { id: "093", name: "Shanti Nagar", slug: "shanti-nagar", group: "central" },
  { id: "094", name: "Wilson Garden", slug: "wilson-garden", group: "central" },
  { id: "095", name: "Ashok Nagar", slug: "ashok-nagar", group: "central" },
  { id: "096", name: "Sampangiram Nagar", slug: "sampangiram-nagar", group: "central" },
  { id: "097", name: "Chickpet", slug: "chickpet", group: "central" },
  { id: "098", name: "Chamrajpet", slug: "chamrajpet", group: "central" },
  { id: "099", name: "Kalasipalya", slug: "kalasipalya", group: "central" },
  { id: "100", name: "Sudhama Nagar", slug: "sudhama-nagar", group: "central" },
  // Outer
  { id: "101", name: "Electronic City", slug: "electronic-city", group: "outer", aliases: ["Electronics City"] },
  { id: "102", name: "Bommasandra", slug: "bommasandra", group: "outer" },
  { id: "103", name: "Chandapura", slug: "chandapura", group: "outer" },
  { id: "104", name: "Attibele", slug: "attibele", group: "outer" },
  { id: "105", name: "Anekal", slug: "anekal", group: "outer" },
  { id: "106", name: "Sarjapur", slug: "sarjapur", group: "outer" },
  { id: "107", name: "Dommasandra", slug: "dommasandra", group: "outer" },
  { id: "108", name: "Varthur", slug: "varthur", group: "outer" },
  { id: "109", name: "Gunjur", slug: "gunjur", group: "outer" },
  { id: "110", name: "Channasandra", slug: "channasandra", group: "outer" },
  { id: "111", name: "Hoskote", slug: "hoskote", group: "outer" },
  { id: "112", name: "Budigere Cross", slug: "budigere-cross", group: "outer" },
  { id: "113", name: "Devanahalli", slug: "devanahalli", group: "outer" },
  { id: "114", name: "Bagalur", slug: "bagalur", group: "outer" },
  { id: "115", name: "Chikkajala", slug: "chikkajala", group: "outer" },
  { id: "116", name: "Doddaballapur", slug: "doddaballapur", group: "outer" },
  { id: "117", name: "Nelamangala", slug: "nelamangala", group: "outer" },
  { id: "118", name: "Madanayakanahalli", slug: "madanayakanahalli", group: "outer" },
  { id: "119", name: "Madavara", slug: "madavara", group: "outer" },
  { id: "120", name: "Kumbalgodu", slug: "kumbalgodu", group: "outer" },
];

export const CITY_SERVICES = [
  "breakfast", "lunch", "dinner", "south-indian-food", "north-indian-food",
  "karnataka-meals", "vegetarian-meals", "non-vegetarian-meals", "family-meals",
  "pg-meals", "office-meals", "bulk-food-orders", "monthly-meal-plans",
  "weekly-meal-plans", "tiffin-service", "function-food",
] as const;

export const SEARCH_ALIASES: Record<string, string> = {
  bangalore: "bengaluru",
  hsr: "hsr-layout",
  "rr nagar": "rajarajeshwari-nagar",
  btm: "btm-layout",
  electronic: "electronic-city",
  electronics: "electronic-city",
  malleswaram: "malleshwaram",
  yeshwantpur: "yeshwanthpur",
  halasuru: "ulsoor",
};
